const rgb = (name) => `rgb(var(--color-${name}) / <alpha-value>)`;

export const themeTokens = Object.freeze({
  colors: {
    background: rgb('background'),
    canvas: rgb('background'),
    surface: {
      DEFAULT: rgb('surface'),
      elevated: rgb('surface-elevated'),
      inverse: rgb('surface-inverse'),
    },
    elevated: rgb('surface-elevated'),
    text: {
      primary: rgb('text-primary'),
      secondary: rgb('text-secondary'),
      muted: rgb('text-muted'),
      inverse: rgb('text-inverse'),
    },
    ink: rgb('text-primary'),
    graphite: rgb('text-secondary'),
    muted: rgb('text-muted'),
    accent: {
      DEFAULT: rgb('accent'),
      hover: rgb('accent-hover'),
      subtle: rgb('accent-subtle'),
      muted: rgb('accent-muted'),
      contrast: rgb('accent-contrast'),
    },
    success: {
      DEFAULT: rgb('success'),
      subtle: rgb('success-subtle'),
      contrast: rgb('success-contrast'),
    },
    warning: {
      DEFAULT: rgb('warning'),
      subtle: rgb('warning-subtle'),
      contrast: rgb('warning-contrast'),
    },
    error: {
      DEFAULT: rgb('error'),
      subtle: rgb('error-subtle'),
      contrast: rgb('error-contrast'),
    },
    danger: rgb('error'),
    border: {
      DEFAULT: rgb('border'),
      strong: rgb('border-strong'),
      muted: rgb('border-muted'),
    },
    line: rgb('border'),
    divider: rgb('divider'),
    overlay: rgb('overlay'),
    hover: rgb('hover'),
    focus: rgb('focus'),
    disabled: {
      DEFAULT: rgb('disabled'),
      bg: rgb('disabled-bg'),
      text: rgb('disabled-text'),
      border: rgb('disabled-border'),
    },
    skeleton: rgb('skeleton'),
    scrollbar: {
      thumb: rgb('scrollbar-thumb'),
      track: rgb('scrollbar-track'),
    },
    selection: {
      DEFAULT: rgb('selection'),
      text: rgb('selection-text'),
    },
    signal: rgb('accent'),
    pulse: rgb('success'),
    cobalt: rgb('focus'),
  },
  typography: {
    fontFamily: {
      display: ['var(--font-display)'],
      heading: ['var(--font-heading)'],
      body: ['var(--font-body)'],
      sans: ['var(--font-body)'],
      mono: ['var(--font-mono)'],
    },
    fontSize: {
      'display-xl': [
        'var(--type-display-xl-size)',
        {
          lineHeight: 'var(--type-display-xl-line-height)',
          letterSpacing: 'var(--tracking-display)',
          fontWeight: 'var(--font-weight-regular)',
        },
      ],
      'display-l': [
        'var(--type-display-l-size)',
        {
          lineHeight: 'var(--type-display-l-line-height)',
          letterSpacing: 'var(--tracking-display)',
          fontWeight: 'var(--font-weight-regular)',
        },
      ],
      'display-m': [
        'var(--type-display-m-size)',
        {
          lineHeight: 'var(--type-display-m-line-height)',
          letterSpacing: 'var(--tracking-display)',
          fontWeight: 'var(--font-weight-regular)',
        },
      ],
      'heading-xl': [
        'var(--type-heading-xl-size)',
        {
          lineHeight: 'var(--type-heading-xl-line-height)',
          letterSpacing: 'var(--tracking-heading)',
          fontWeight: 'var(--font-weight-medium)',
        },
      ],
      'heading-l': [
        'var(--type-heading-l-size)',
        {
          lineHeight: 'var(--type-heading-l-line-height)',
          letterSpacing: 'var(--tracking-heading)',
          fontWeight: 'var(--font-weight-medium)',
        },
      ],
      'heading-m': [
        'var(--type-heading-m-size)',
        {
          lineHeight: 'var(--type-heading-m-line-height)',
          letterSpacing: 'var(--tracking-heading)',
          fontWeight: 'var(--font-weight-medium)',
        },
      ],
      'heading-s': [
        'var(--type-heading-s-size)',
        {
          lineHeight: 'var(--type-heading-s-line-height)',
          letterSpacing: 'var(--tracking-heading)',
          fontWeight: 'var(--font-weight-medium)',
        },
      ],
      'body-xl': [
        'var(--type-body-xl-size)',
        {
          lineHeight: 'var(--type-body-xl-line-height)',
          letterSpacing: 'var(--tracking-body)',
          fontWeight: 'var(--font-weight-regular)',
        },
      ],
      'body-l': [
        'var(--type-body-l-size)',
        {
          lineHeight: 'var(--type-body-l-line-height)',
          letterSpacing: 'var(--tracking-body)',
          fontWeight: 'var(--font-weight-regular)',
        },
      ],
      'body-m': [
        'var(--type-body-m-size)',
        {
          lineHeight: 'var(--type-body-m-line-height)',
          letterSpacing: 'var(--tracking-body)',
          fontWeight: 'var(--font-weight-regular)',
        },
      ],
      'body-small': [
        'var(--type-body-small-size)',
        {
          lineHeight: 'var(--type-body-small-line-height)',
          letterSpacing: 'var(--tracking-body)',
          fontWeight: 'var(--font-weight-regular)',
        },
      ],
      caption: [
        'var(--type-caption-size)',
        {
          lineHeight: 'var(--type-caption-line-height)',
          letterSpacing: 'var(--tracking-caption)',
          fontWeight: 'var(--font-weight-regular)',
        },
      ],
      label: [
        'var(--type-label-size)',
        {
          lineHeight: 'var(--type-label-line-height)',
          letterSpacing: 'var(--tracking-label)',
          fontWeight: 'var(--font-weight-medium)',
        },
      ],
      button: [
        'var(--type-button-size)',
        {
          lineHeight: 'var(--type-button-line-height)',
          letterSpacing: 'var(--tracking-button)',
          fontWeight: 'var(--font-weight-medium)',
        },
      ],
      navigation: [
        'var(--type-navigation-size)',
        {
          lineHeight: 'var(--type-navigation-line-height)',
          letterSpacing: 'var(--tracking-navigation)',
          fontWeight: 'var(--font-weight-medium)',
        },
      ],
    },
    fontWeight: {
      regular: 'var(--font-weight-regular)',
      medium: 'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold: 'var(--font-weight-bold)',
    },
    letterSpacing: {
      display: 'var(--tracking-display)',
      heading: 'var(--tracking-heading)',
      body: 'var(--tracking-body)',
      caption: 'var(--tracking-caption)',
      label: 'var(--tracking-label)',
      button: 'var(--tracking-button)',
      navigation: 'var(--tracking-navigation)',
    },
    lineHeight: {
      tight: 'var(--leading-tight)',
      snug: 'var(--leading-snug)',
      normal: 'var(--leading-normal)',
      relaxed: 'var(--leading-relaxed)',
      spacious: 'var(--leading-spacious)',
    },
  },
  spacing: {
    'space-4': 'var(--space-4)',
    'space-8': 'var(--space-8)',
    'space-12': 'var(--space-12)',
    'space-16': 'var(--space-16)',
    'space-24': 'var(--space-24)',
    'space-32': 'var(--space-32)',
    'space-40': 'var(--space-40)',
    'space-48': 'var(--space-48)',
    'space-64': 'var(--space-64)',
    'space-80': 'var(--space-80)',
    'space-96': 'var(--space-96)',
    'space-120': 'var(--space-120)',
    'space-160': 'var(--space-160)',
    'space-200': 'var(--space-200)',
    'section-sm': 'var(--section-padding-sm)',
    'section-md': 'var(--section-padding-md)',
    'section-lg': 'var(--section-padding-lg)',
    'scroll-progress': 'var(--layout-scroll-progress-height)',
    'control-sm': 'var(--control-sm)',
    'control-md': 'var(--control-md)',
    'control-lg': 'var(--control-lg)',
    'icon-16': 'var(--icon-16)',
    'icon-20': 'var(--icon-20)',
    'icon-24': 'var(--icon-24)',
    'icon-32': 'var(--icon-32)',
    'icon-48': 'var(--icon-48)',
    'container-sm': 'var(--container-padding-sm)',
    'container-md': 'var(--container-padding-md)',
    'container-lg': 'var(--container-padding-lg)',
    'fade-distance': 'var(--motion-fade-distance)',
    'reveal-distance': 'var(--motion-reveal-distance)',
  },
  breakpoints: {
    mobile: '390px',
    xs: '390px',
    sm: '640px',
    tablet: '768px',
    md: '768px',
    desktop: '1024px',
    lg: '1024px',
    wide: '1280px',
    xl: '1280px',
    '2xl': '1440px',
  },
  radius: {
    small: 'var(--radius-small)',
    medium: 'var(--radius-medium)',
    large: 'var(--radius-large)',
    xl: 'var(--radius-xl)',
    full: 'var(--radius-full)',
    sm: 'var(--radius-small)',
    DEFAULT: 'var(--radius-medium)',
    lg: 'var(--radius-large)',
  },
  shadow: {
    none: 'none',
    hairline: 'var(--shadow-hairline)',
    soft: 'var(--shadow-soft)',
    elevated: 'var(--shadow-elevated)',
    focus: 'var(--shadow-focus)',
    inset: 'var(--shadow-inset)',
  },
  motion: {
    duration: {
      fast: 'var(--motion-duration-fast)',
      medium: 'var(--motion-duration-medium)',
      base: 'var(--motion-duration-medium)',
      slow: 'var(--motion-duration-slow)',
      'extra-slow': 'var(--motion-duration-extra-slow)',
    },
    easing: {
      standard: 'var(--motion-ease-standard)',
      luxury: 'var(--motion-ease-luxury)',
      emphasized: 'var(--motion-ease-emphasized)',
      entrance: 'var(--motion-ease-entrance)',
      exit: 'var(--motion-ease-exit)',
    },
    transitionProperty: {
      ui: 'color, background-color, border-color, box-shadow, opacity, transform',
      surface: 'background-color, border-color, box-shadow',
      reveal: 'opacity, transform, filter',
    },
    scale: {
      hover: 'var(--motion-hover-scale)',
      active: 'var(--motion-active-scale)',
    },
    blur: {
      soft: 'var(--motion-blur-soft)',
      reveal: 'var(--motion-blur-reveal)',
    },
    keyframes: {
      fade: {
        from: { opacity: '0', transform: 'translateY(var(--motion-fade-distance))' },
        to: { opacity: '1', transform: 'translateY(0)' },
      },
      reveal: {
        from: {
          opacity: '0',
          filter: 'blur(var(--motion-blur-reveal))',
          transform: 'translateY(var(--motion-reveal-distance))',
        },
        to: { opacity: '1', filter: 'blur(0)', transform: 'translateY(0)' },
      },
      shimmer: {
        '0%': { backgroundPosition: '200% 0' },
        '100%': { backgroundPosition: '-200% 0' },
      },
      spin: {
        to: { transform: 'rotate(360deg)' },
      },
    },
    animation: {
      fade: 'fade var(--motion-duration-slow) var(--motion-ease-entrance) both',
      reveal: 'reveal var(--motion-duration-extra-slow) var(--motion-ease-luxury) both',
      shimmer: 'shimmer 1.6s var(--motion-ease-standard) infinite',
      spin: 'spin 900ms linear infinite',
    },
  },
  opacity: {
    disabled: 'var(--opacity-disabled)',
    muted: 'var(--opacity-muted)',
    overlay: 'var(--opacity-overlay)',
  },
  layout: {
    container: 'var(--layout-container-width)',
    content: 'var(--layout-content-width)',
    prose: 'var(--layout-prose-width)',
    narrow: 'var(--layout-narrow-width)',
    full: '100%',
    pageGutter: 'var(--container-padding-md)',
    maxWidth: {
      container: 'var(--layout-container-width)',
      content: 'var(--layout-content-width)',
      prose: 'var(--layout-prose-width)',
      narrow: 'var(--layout-narrow-width)',
      full: '100%',
    },
    sectionPadding: {
      sm: 'var(--section-padding-sm)',
      md: 'var(--section-padding-md)',
      lg: 'var(--section-padding-lg)',
    },
    height: {
      navbar: 'var(--layout-navbar-height)',
      footer: 'var(--layout-footer-height)',
      hero: 'var(--layout-hero-height)',
    },
    minHeight: {
      hero: 'var(--layout-hero-height)',
      screen: '100vh',
    },
    containerPadding: {
      DEFAULT: 'var(--container-padding-sm)',
      md: 'var(--container-padding-md)',
      lg: 'var(--container-padding-lg)',
    },
    containerScreens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1440px',
    },
  },
  zIndex: {
    base: '0',
    raised: '10',
    sticky: '20',
    overlay: '40',
    modal: '50',
    skip: '60',
  },
});
